"""
prepare_features.py — Step 3: Feature Preparation (Benchmark Model)
───────────────────────────────────────────────────────────────────
PySpark job that transforms the raw feature snapshot into train/test
splits ready for model training.

Operations (in order):
  1. Manifest Loading
       Reads the manifest generated by extract_features to grab selected features.
       
  2. Temporal Stratification Split
       Ensures chronological order is maintained.
       Identifies the exact cutoff timestamp to ensure the test set
       contains exactly `test_ratio` proportion of the total FAILURES.

  3. Training Data Imputation Baselines
       Calculates the median for all selected features purely on the training set
       to be used as a fallback in the inference service.

  4. Feature manifest
       Updates feature_manifest.json with train/test stats and medians.
"""

import sys
import argparse
import logging
import json
from datetime import datetime, timedelta, timezone

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql.functions import col, row_number, lit, percentile_approx
from pyspark.sql.window import Window

from common.config import ServiceConfig

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

config = ServiceConfig()

PREPARE_PIPELINE_VERSION = "1.0.0"

# Constants
MINIO_ENDPOINT = config.minio_endpoint
MINIO_ACCESS_KEY = config.minio_access_key
MINIO_SECRET_KEY = config.minio_secret_key
CATALOG_URI = config.catalog_uri
CATALOG_USER = config.catalog_user
CATALOG_PASSWORD = config.catalog_password
S3_WAREHOUSE_PATH = config.minio_warehouse

# Excluded silver_created_at and processing_logic
META_COLS = [
    "observation_id", "process_timestamp", "lot_id", "wafer_status", "label_numeric", 
    "missing_sensor_count", "binary_label", "missing_sensor_rate", "snapshot_timestamp", 
    "snapshot_lookback_days"
]

CATEGORICAL_FEATURES = [
    "line_id", "tester_id", "shift"
]

def _write_iceberg(df: DataFrame, table: str, spark: SparkSession) -> None:
    table_exists = spark.catalog.tableExists(table)
    writer = (
        df.writeTo(table)
        .tableProperty("write.format.default", "parquet")
    )
    if table_exists:
        writer.overwritePartitions()
    else:
        writer.create()
    logger.info("Written %d rows to %s", df.count(), table)


def create_spark_session(
    minio_endpoint: str,
    minio_access_key: str,
    minio_secret_key: str,
    catalog_uri: str,
    catalog_user: str,
    catalog_password: str,
    warehouse_path: str
    ) -> SparkSession:
    """Configures Spark with Iceberg and MinIO capabilities."""
    return SparkSession.builder \
        .appName("SECOM_Raw_to_Bronze") \
        .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions") \
        .config("spark.sql.catalog.secom_catalog", "org.apache.iceberg.spark.SparkCatalog") \
        .config("spark.sql.catalog.secom_catalog.type", "jdbc") \
        .config("spark.sql.catalog.secom_catalog.uri", catalog_uri) \
        .config("spark.sql.catalog.secom_catalog.jdbc.user", catalog_user) \
        .config("spark.sql.catalog.secom_catalog.jdbc.password", catalog_password) \
        .config("spark.sql.catalog.secom_catalog.jdbc.schema-version", "V1") \
        .config("spark.sql.catalog.secom_catalog.warehouse", warehouse_path) \
        .config("spark.sql.catalog.secom_catalog.io-impl", "org.apache.iceberg.hadoop.HadoopFileIO") \
        .config("spark.hadoop.fs.s3a.endpoint", minio_endpoint) \
        .config("spark.hadoop.fs.s3a.access.key", minio_access_key) \
        .config("spark.hadoop.fs.s3a.secret.key", minio_secret_key) \
        .config("spark.hadoop.fs.s3a.path.style.access", "true") \
        .config("spark.hadoop.fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
        .config("spark.hadoop.fs.s3.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem") \
        .config("spark.hadoop.fs.s3a.aws.client.region", "us-east-1") \
        .getOrCreate()

def main():
    from common.config import ServiceConfig
    config = ServiceConfig()

    # Parse the exact file paths passed by Airflow
    parser = argparse.ArgumentParser(description="SECOM ML — Feature Preparation")
    parser.add_argument("--test-ratio",  type=float, default=0.20)
    parser.add_argument("--feature-table", default="secom_catalog.ml.feature_snapshot")
    parser.add_argument("--train-table",   default="secom_catalog.ml.train_features")
    parser.add_argument("--test-table",    default="secom_catalog.ml.test_features")
    args = parser.parse_args()

    manifest_path = "/tmp/feature_manifest.json"
    try:
        with open(manifest_path, "r") as f:
            manifest = json.load(f)
        feature_status_dict = manifest.get("feature_status", {})
        active_features = [col_name for col_name, status in feature_status_dict.items() if status == "active"]

        if not active_features:
            logger.warning("No active features found in manifest. Model might fail.")
        else:
            logger.info("Loaded %d active features from manifest.", len(active_features))
    except FileNotFoundError:
        logger.error("Manifest file not found. Ensure extract_features.py ran successfully.")
        sys.exit(1)
    except json.JSONDecodeError:
        logger.error("Failed to decode manifest file. Data may be corrupt.")
        sys.exit(1)


    spark = create_spark_session(
        minio_endpoint=config.minio_endpoint,
        minio_access_key=config.minio_access_key,
        minio_secret_key=config.minio_secret_key,
        catalog_uri=config.catalog_uri,
        catalog_user=config.catalog_user,
        catalog_password=config.catalog_password,
        warehouse_path=config.minio_warehouse
    )
    logger.info("Spark Session initialized.")

    # ── Load feature snapshot 
    logger.info("Loading feature snapshot from %s", args.feature_table)
    df = spark.table(args.feature_table)
    total_rows = df.count()

    # ── Temporal Stratification Split
    # 1. Calculate how many failures exist total
    total_fails = df.filter(col("binary_label") == 1).count()
    min_test_fails = int(total_fails * args.test_ratio)

    logger.info("Total rows: %d | Total Failures: %d | Target Test Failures: %d", 
                total_rows, total_fails, min_test_fails)

    if min_test_fails == 0:
        logger.warning("Not enough failures to stratify! Defaulting to a standard time split.")
        w_global = Window.orderBy(col("process_timestamp").desc())
        df = df.withColumn("row_num", row_number().over(w_global))
        split_idx = int(total_rows * args.test_ratio)
        cutoff_row = df.filter(col("row_num") == split_idx).select("process_timestamp").first()
        cutoff_timestamp = cutoff_row["process_timestamp"]
        df = df.drop("row_num")

    else:
        # 2. Isolate failures and rank them backward by time (1 = most recent failure)
        fails_df = df.filter(col("binary_label") == 1)
        w_fails_backward = Window.orderBy(col("process_timestamp").desc())
        fails_df = fails_df.withColumn("fail_rank_desc", row_number().over(w_fails_backward))
        
        # 3. Find the exact timestamp of the failure that hits our threshold
        cutoff_row = fails_df.filter(col("fail_rank_desc") == min_test_fails).select("process_timestamp").first()
        cutoff_timestamp = cutoff_row["process_timestamp"]
    
    logger.info("Temporal Split Cutoff Timestamp: %s", cutoff_timestamp)

    # 4. Split the main dataframe based on that timestamp
    train_df = df.filter(col("process_timestamp") < cutoff_timestamp)
    test_df  = df.filter(col("process_timestamp") >= cutoff_timestamp)
    train_df = train_df.withColumn("preparation_pipeline_version", lit(PREPARE_PIPELINE_VERSION))
    test_df = test_df.withColumn("preparation_pipeline_version", lit(PREPARE_PIPELINE_VERSION))

    train_fails = train_df.filter(col("binary_label") == 1).count()
    test_fails = test_df.filter(col("binary_label") == 1).count()

    logger.info("Split Complete:")
    logger.info("  Train: %d total rows (%d fails)", train_df.count(), train_fails)
    logger.info("  Test:  %d total rows (%d fails)", test_df.count(), test_fails)

    # ── Write to Iceberg
    spark.sql("CREATE NAMESPACE IF NOT EXISTS secom_catalog.ml")
    _write_iceberg(train_df, args.train_table, spark)
    _write_iceberg(test_df,  args.test_table,  spark)
    
    # Calculate Medians on the Training Data
    logger.info("Calculating baseline medians from training data...")
    train_medians = {}

    if active_features:
        agg_exprs = [percentile_approx(col(f"`{c}`"), 0.5).alias(c) for c in active_features]
        medians_row = train_df.agg(*agg_exprs).collect()[0]

        for c in active_features:
            val = medians_row[c]
            if val is None:
                logger.error("Data integrity failure: Median for active feature '%s' returned None.", c)
                raise ValueError(f"Failed to calculate median for active feature: {c}. Expected a numeric value, got None.")
            train_medians[c] = float(val)
    else:
        logger.warning("No feature columns available to calculate medians.") 

    # Calculate Modes on Training Data (Categorical)
    logger.info("Calculating baseline modes for categorical features...")
    train_modes = {}
    available_cat_cols = [c for c in CATEGORICAL_FEATURES if c in train_df.columns]
    
    for c in available_cat_cols:
        # Group by the category, count occurrences, sort descending, and grab the top one
        mode_row = train_df.filter(col(c).isNotNull()).groupBy(c).count().orderBy(col("count").desc()).first()
        if mode_row:
            train_modes[c] = mode_row[c]
        else:
            logger.warning("Categorical feature '%s' is entirely null in training data. Defaulting to 'UNKNOWN'.", c)
            train_modes[c] = "UNKNOWN"


    manifest.update({
        "preparation_pipeline_version": PREPARE_PIPELINE_VERSION,
        "active_features_list": active_features,
        "lag_features": [],
        "categorical_features": available_cat_cols,
        "categorical_modes":train_modes,
        "medians": train_medians,
        "train_rows": train_df.count(),
        "test_rows": test_df.count(),
        "train_fails": train_fails,
        "test_fails": test_fails,
        "test_ratio": args.test_ratio,
        "cutoff_timestamp": cutoff_timestamp.strftime("%Y-%m-%d %H:%M:%S") if cutoff_timestamp else None,
        "prepared_at": datetime.now(timezone.utc).isoformat(),
    })

    print(json.dumps(manifest, indent=2))

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    logger.info("Appended train/test details and updated manifest at %s", manifest_path)

    spark.stop()

if __name__ == "__main__":
    main()