[tool.poetry]
name = "synthetic-data-generator"
version = "0.1.0"
description = "This is a module to generate synthetic dataset based on the SECOM dataset, with capability to introdu"
authors = ["ccl"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "3.0.2"
scipy = "1.17.1"
s3fs = "2026.3.0"
numpy = "2.4.4"
pydantic = "2.13.0"
pydantic-settings = "2.13.1"
nats-py = "2.14.0"
pyarrow = "23.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
