name: 'secom_analytics'
version: '0.1.0'
config-version: 2
profile: 'secom_analytics'

models:
  secom_analytics:
    staging:
      +materialized: ephemeral
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
      +file_format: parquet
    gold:
      +materialized: table
      +schema: gold
      +file_format: parquet

vars:
  spc_phase1_sample_size: 100
  oee_scheduled_shifts_per_day: 1.0
  oee_theoretical_max_wafers_per_day: 25.0