name: 'secom_analytics'
version: '0.1.0'
config-version: 1
profile: 'secom_analytics'

models:
  secom_analytics:
    staging:
      materialized: view
      schema: bronze
    silver:
      materialized: table
      schema: silver
      file_format: iceberg