name: 'secom_analytics'
version: '0.1.0'
config-version: 2
profile: 'secom_analytics'

models:
  secom_analytics:
    staging:
      +materialized: ephemeral
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
      +file_format: parquet
    gold:
      +materialized: table
      +schema: gold
      +file_format: parquet